### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by ghost**
Fix issue #27

### CODE REVIEW

**Comment by brvier** [comment]
Thanks a lot.

**Comment by rugk** [comment]
When will this be merged?

**Comment by rugk** [comment]
Wait, there is no reason to just close it…

@khertan do you wanna merge this or at least use the icon files or what?

**Comment by brvier** [comment]
Oh my ... just see all github notification ends in spam folder ... 

So of course will be integrated. It s already  in next release in master. (Still need to fix records calculation by type of sports)

Regards

Benoît HERVIER - http://rvier.fr

**Pull request closed without merging**
